/**
 * Public CMS / Medicare data keyed by CCN. Generated by scripts/fetch-hospital-public-data.mjs
 */
import profilesJson from '@/data/hospital-public-profiles.json';
import type { TeamHospital } from '@/data/team-hospitals';

export interface HospitalGeneralInfo {
  facilityName: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  county: string;
  phone: string;
  hospitalType: string;
  ownership: string;
  emergencyServices: string;
  birthingFriendly: string;
  overallRating: string | null;
  readmMeasuresWorse: string | null;
  readmMeasuresBetter: string | null;
  safetyMeasuresBetter: string | null;
}

export interface HospitalCostReport {
  fiscalYearEnd: string;
  numberOfBeds: string | null;
  totalDischarges: string | null;
  fteEmployees: string | null;
  medicareCbsaNumber: string | null;
  ruralUrban: string | null;
}

export interface HrrpMeasure {
  measure: string;
  excessReadmissionRatio: number;
  predictedRate: number | null;
  expectedRate: number | null;
}

export interface HospitalHrrp {
  fiscalYear: string;
  measures: HrrpMeasure[];
  avgExcessReadmissionRatio?: number | null;
  conditionsAbovePeers?: number;
}

export interface HospitalHacrp {
  fiscalYear: string;
  totalHacScore: number | null;
  paymentReduction: string | null;
  psi90: number | null;
}

export interface HospitalHcahps {
  starRating: string | null;
  completedSurveys: number | null;
  responseRatePercent: number | null;
}

export interface HospitalHvbp {
  fiscalYear: string;
  totalPerformanceScore: number | null;
  clinicalOutcomes: number | null;
  patientExperience: number | null;
  safety: number | null;
  efficiency: number | null;
}

export interface HospitalMspb {
  score: number | null;
  measureName: string;
}

export interface HospitalPublicProfile {
  ccn: string;
  general: HospitalGeneralInfo;
  costReport?: HospitalCostReport;
  hrrp?: HospitalHrrp;
  hacrp?: HospitalHacrp;
  hcahps?: HospitalHcahps;
  hvbp?: HospitalHvbp;
  mspb?: HospitalMspb;
}

interface ProfilesFile {
  generatedAt: string;
  sources: { id: string; dataset?: string; url: string }[];
  byCcn: Record<string, HospitalPublicProfile>;
}

const store = profilesJson as ProfilesFile;

export function getPublicProfileByCcn(ccn: string | undefined): HospitalPublicProfile | undefined {
  if (!ccn) return undefined;
  const key = ccn.replace(/\D/g, '').padStart(6, '0');
  return store.byCcn[key];
}

export function getPublicProfile(hospital: TeamHospital): HospitalPublicProfile | undefined {
  return getPublicProfileByCcn(hospital.ccn);
}

export const publicProfilesGeneratedAt = store.generatedAt;
export const publicProfileSources = store.sources;
